### ISSUE TITLE
godot-community permissions: allow repo donors access to their own repos.

### ISSUE THREAD

**Issue by willnationsdev** [godot-community/godot-ideas#2]
**Describe the project you are working on:**
Managing the godot-community organization.

**Describe how this feature / enhancement will help your project:**
If someone donates a repository to the organization, then they will have fully transferred ownership. Ideally, we would then find a way to allow them to still have access to the code directly, but without them also having write access to the rest of the organization's public repositories.

My initial thought is: anyone who wishes to join the organization to host a project/addon/plugin/module should be freely able to do so, BUT those people should not be able to arbitrarily mess with repositories that have been donated by someone else, unless they have higher admin privileges.

However, the only thing I can think of would be admins manually creating a Team for every newly created repository and handing write permissions for that repo exclusively to admins and that Team, rather than any Member. This would be a lot of work, but doable. Perhaps using `godot-ideas` with a special label for people to submit requests for their repos to be added.

The alternative is making organization membership much more exclusive and people would be donating their work wholesale to the organization (without them having individual access to their own donated repository - NOT ideal).

Is there some middleground? Please, throw your ideas out there, especially if you have GitHub organization experience. What would be the best way to handle this?

**Comment by Xrayez** [comment]
I don't think there'd be a lot of people who would be willing to transfer their repositories to this organization for the sake of it though (such repository would have to cater to most community needs). So what seems to be a lot of work could be trivial to do at first stages, at least for now.

**Comment by lawnjelly** [comment]
Do you need to maintain the repositories there, can't you just link to them? A searchable tree of info pages with links would be cool:

e.g.
```
3D
	Graphics
		Animation
		Shaders
		etc
	Sound
	Editor
	Other
2D
	Graphics
	Sound
	Editor
	Other
```
Then have the links able to appear in more than one section (e.g. some addons may work for 3d and 2d).

Otherwise you'll just end up with a long list of repositories (which maybe few people would look through). And as Xrayez says, at least at first it might be difficult to convince authors to transfer their repositories.

**Comment by Xrayez** [comment]
There's similar list already like [awesome-godot](https://github.com/Calinou/awesome-godot) though.

**Comment by willnationsdev** [comment]
@lawnjelly 

> Do you need to maintain the repositories there, can't you just link to them?

Well, I don't know if it's at all similar for others, but at least for me, I tend to create a *lot* of branches when I'm working on things. And many of them are WIPs, some of which make it to the end, some of which don't (as I'm just experimenting with ideas and whatnot). I also work on stuff between multiple computers, so I often push these branches to my origin just so that I can pull them back down from another machine.

So, for a third party that comes to my plugin and checks it out, if they examine the braches that exist, they'll end up seeing a ton of stuff that isn't ready for use that is just my own miscellaneous work. `godot-next` was full of these, with only 1 or 2 branches actually intended for others (`master` and `3.1`). Now that I have transferred it over to the godot-community repository, there can be a publicly recognized one that is separate from my own. I can strip away most of the features that people don't need to see until I complete them privately and merge them in.

@Xrayez 

> So what seems to be a lot of work could be trivial to do at first stages, at least for now.

Sounds good. I haven't gotten anyone wanting move something over, so I suppose that's fine.

> There's similar list already like awesome-godot though.

That actually would be a decent contender for moving over here though. That way anyone in the organization can merge people's requests to add their stuff to it. Honestly though, using GitHub taga is a lot more effective. It'd be good if people (like me) used them more often...

**Comment by willnationsdev** [comment]
Oh, it turns out that my concerns for this are a moot point. I just started investigating things and it looks like if you go to the People page of the godot-community dashboard, the Owner has a "Manage" button beside each user which lets me dictate who has admin/read/write access to repositories in the organization. And it seems like those who transfer ownership to the repo automatically are given Admin access to the repo by default while everyone else only has read access (*exactly* what we wanted). Soooo...there's no work to be done! Yay.

I'm gonna go ahead and close this issue then.
